[package]
name = "venue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.0.1"

[lib]
name = "venue"
crate-type = ["cdylib"]
